# Generated by Django 4.1.7 on 2023-03-12 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('web', models.CharField(blank=True, max_length=200)),
                ('enlaced_number_system', models.IntegerField()),
                ('enlaced_code_system', models.CharField(blank=True, max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_carriage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('CF', 'CAPITAL FEDERAL'), ('BA', 'BUENOS AIRES'), ('CA', 'CATAMARCA'), ('CH', 'CHACO'), ('CU', 'CHUBUT'), ('CO', 'CÓRDOBA'), ('CR', 'CORRIENTES'), ('ER', 'ENTRE RÍOS'), ('FO', 'FORMOSA'), ('JU', 'JUJUY'), ('LP', 'LA PAMPA'), ('LR', 'LA RIOJA'), ('MZ', 'MENDOZA'), ('MI', 'MISIONES'), ('NQ', 'NEUQUÉN'), ('RN', 'RÍO NEGRO'), ('SA', 'SALTA'), ('SJ', 'SAN JUAN'), ('SL', 'SAN LUIS'), ('SC', 'SANTA CRUZ'), ('SF', 'SANTA FE'), ('SE', 'SANTIAGO DEL ESTERO'), ('TF', 'TIERRA DEL FUEGO'), ('TU', 'TUCUMÁN')], default='BA', max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_price_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_color', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('materials', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('units_per_package', models.IntegerField()),
                ('observations', models.TextField()),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='orders.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initial_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('enlaced_number_system', models.IntegerField()),
                ('enlaced_code_system', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_price_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('billing', models.CharField(choices=[('1', 'PRO'), ('2', 'FC')], default='2', max_length=1)),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriage_order', to='orders.carriage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='orders.client')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_order', to='orders.price_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line_price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line_price_list', to='orders.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_line_price', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('billing', models.CharField(choices=[('1', 'PRO'), ('2', 'FC')], default='2', max_length=1)),
                ('discount', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_line_order', to='orders.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_order', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line_order', to='orders.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_line_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
